# Generated by Django 4.2.7 on 2023-12-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_bath_listing_bed_listing_price_listing_sqft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bath',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
